# Site settings
title: diff.mx
email: diffalot@diff.mx
description: > # this means to ignore newlines until "baseurl:"
        the online collection of Andrew Davis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://diff.mx" # the base hostname & protocol for your site
permalink: /:year/:month/:title
twitter_username: diffalot
gitlab_username:  diffalot

# Build settings
markdown: kramdown
