# Site settings
title: diff.mx
email: diffalot@diff.mx
description: > # this means to ignore newlines until "baseurl:"
  selected work by Andrew Davis
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://diff.mx/" # the base hostname & protocol for your site
twitter_username: diffalot
github_username:  diffalot

# Build settings
markdown: kramdown
